import './globals.css'
import Header from './components/Header'

export const metadata = {
  title: 'Southern Planners | Event Planners & Stylist',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <div className="content_wrapper">
          <Header/>
          {children}
        </div>
      </body>
    </html>
  )
}
